### ISSUE TITLE
[Question] Modify when the timing starts

### ISSUE THREAD

**Issue by russellhoff** [zendesk/timetracking_app#73]
I've some questions I want you to solve them, please...

The first one I don't know whether I'm able to modify the code for myself and then, later, install my "fork" on zendesk.

The changes I wan't to accomplish are quite straightforward. Currently, the timing starts when the ticket is opened until it gets resolved. I'd want to modify the opening event to when a ticket is assigned to an operator. Would it be possible?

Additionally, I'd like to disable the ability of pausing/stopping/resuming/etc the timing. Would it also be possible?

Afterwards, I'd be adding some customisations.

Thank you!

**Comment by sostopher** [comment]
Changing when the timer starts will not be supported or added.

Hiding the controls is now a feature.
