### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by minde-revel** [zendesk/timetracking_app#77]
After last zendesk update, this app is not working. When I submit the ticket and after trying to click on "Cancel Submission" nothing happens and ticket gets submitted.

**Comment by sandlerr** [comment]
Hi @minde-revel thanks for creating this issue. Since this problem seems localised to a specific account, can we continue this conversation through a ticket? Please create one through [this link](https://help.zendesk.com/hc/en-us/requests/new) or via email to support@zendesk.com

**Comment by minde-revel** [comment]
Hey @sandlerr I have created ticket already and agent sent me here. Here is zendesk ticket #2061549 
or do I need to create another one?

**Comment by sandlerr** [comment]
Hi @minde-revel your existing ticket is for a different app, not the Time Tracking app. Are you having problems specifically with time logs or other functionality related to time tracking?

**Comment by minde-revel** [comment]
ohh sorry @sandlerr how i missed that, was submitting ticket for OOPS app.

**Comment by sandlerr** [comment]
No problem - hope you find the solution!
