### ISSUE TITLE
[Feature idea] unpause timer when agent types in comment field

### ISSUE THREAD

**Issue by jpalmieri** [zendesk/timetracking_app#82]
@zendesk/vegemite

My team has recently been attempting to improve the time tracking on our tickets, and noticed that one thing that sometimes makes the tracking less accurate is this situation:

> Agent manually pauses timer (e.g., when someone else interrupts agent from working on the ticket), then Agent goes back to working on the ticket, but forgets to unpause the timer.

The result is that the *recorded* time spent on the ticket is less than the *actual* time spent on the ticket.

My team had this idea: automatically unpause the timer when the agent starts typing in the comment field (i.e., on `comment.text.changed`). I thought a better feature might be to instead display a modal on this event (when the timer is paused), asking the agent if they want to unpause the timer.

I'd to work on this feature, but it's in our best interest to have the change committed to this repo, so that we get any additional updates for this app (instead of being tied to our own private version of the app).

Does this feature sound like something that is likely to be approved for the production version of the app, if I were to do the work for it myself?

Thanks for your time!

**Comment by aculligan** [comment]
This is a great idea. You might also want to unpause the timer when other ticket fields change, and not just on `comment.text.change`.

**Comment by sandlerr** [comment]
This is a great idea, we'd be very happy with such a contribution, especially if it can be gated behind a setting so there isn't unexpected impact on existing users.

**Comment by jpalmieri** [comment]
Great! Thanks for getting back to me. I'll send a PR soonish.
